### ISSUE TITLE
[Feature] Add a glowing parameter (boolean)

### ISSUE THREAD

**Issue by mathieulievre** [Rapha149/SignGUI#16]
### Is your feature request related to a problem?

When writing in white, the color does not appear white but gray-ish in the GUI. Working with resource packs that change the sign GUI itself, it can become annoying.

### What solution would you like?

Having a new boolean parameter (not mandatory, to avoid breaking any code using older versions of the API) to enable glowing on the sign

### Describe alternatives you've considered

—

### Any additional comments?

I don't know which obfuscated method needs to be called but with the mappings I've found `net.minecraft.world.level.block.entity.SignText#setHasGlowingText(boolean)`

**Comment by Rapha149** [comment]
Good idea, I hadn't thought about that.
However, I'm currently on vacation but I will see if it's possible and implement it in about 2-3 weeks.

**Comment by mathieulievre** [comment]
Perfect, enjoy your vacation!

**Comment by BoBkiNN** [comment]
But text is not glowing in the sign UI. This change is visible only on block itself

**Comment by mathieulievre** [comment]
There is for sure a difference in the render of the text color in the GUI when the sign has the glowing effect. I've only tested this using white color, but there might be a difference with other colors too.

**Comment by BoBkiNN** [comment]
Wow, i tested it and there is really difference. My apologies

**Comment by Rapha149** [comment]
The option is implemented and will be pushed with the next update (today or in the next few days)

**Comment by Rapha149** [comment]
The new release is published, as soon as it's published on Maven (which takes a few hours) you can use the glowing option!
