### ISSUE TITLE
[Bug] Unable to open sign GUI on Paper 1.21.1

### ISSUE THREAD

**Issue by CubeCrafter72** [Rapha149/SignGUI#21]
### API version

2.4.0

### Server software and version

Paper 1.21.1

### Steps to reproduce

```bash
open a sign GUI
```

### Expected behaviour

the sign should open as expected

### What is actually happening?

console error: https://pastebin.com/1p6zS6t9

**Comment by Rapha149** [comment]
Thanks for reporting! Since the NMS version didn't change I didn't think I had to update the API but they made a change that broke something. Should be fixed in the new release.
