### ISSUE TITLE
Maven repository not found

### ISSUE THREAD

**Issue by cmptrwhz** [Rapha149/SignGUI#7]
When I attempt to add your dependency to my project I am getting an error stating your groupId is not being found.

**Comment by cmptrwhz** [comment]
`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.cmptrwhz</groupId>
  <artifactId>DezoMarket</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>DezoMarket</name>

  <properties>
    <java.version>1.8</java.version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version>
        <configuration>
          <source>${java.version}</source>
          <target>${java.version}</target>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <version>3.2.4</version>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
    <resources>
      <resource>
        <directory>src/main/resources</directory>
        <filtering>true</filtering>
      </resource>
    </resources>
  </build>

  <repositories>
      <repository>
          <id>spigotmc-repo</id>
          <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
      </repository>
      <repository>
          <id>sonatype</id>
          <url>https://oss.sonatype.org/content/groups/public/</url>
      </repository>
  </repositories>

  <dependencies>
      <dependency>
          <groupId>org.spigotmc</groupId>
          <artifactId>spigot-api</artifactId>
          <version>1.20.4-R0.1-SNAPSHOT</version>
          <scope>provided</scope>
      </dependency>
      <dependency>
          <groupId>net.luckperms</groupId>
          <artifactId>api</artifactId>
          <version>5.4</version>
          <scope>provided</scope>
      </dependency>
      <dependency>
          <groupId>de.rapha149.signgui</groupId>
          <artifactId>signgui</artifactId>
          <version>2.3.2</version>
      </dependency>
  </dependencies>
</project>`

**Comment by cmptrwhz** [comment]
ugh not sure why the pom isn't showing correctly with the <> code function of this editor

**Comment by Rapha149** [comment]
I edited your comment to make it look better, the trick is to use that symbol three times like this:
\`\`\`pom

Code

\`\`\`

Now your pom.xml does look good, do you get an error while compiling or do you get an error when the plugin is running on the server?

**Comment by cmptrwhz** [comment]
I am sorry there must have been a huge delay in IntelliJ resolving the dependency it is not showing as failed anymore. I added it an hour ago and now it shows as being found.

**Comment by cmptrwhz** [comment]
The error I was getting is when I added the dependency directly to my POM file. IntelliJ was stating it could not resolve it. But everything is ok as it now is showing as resolved. I did close IntelliJ and reopen it so maybe that forced it refresh itself and links?

**Comment by Rapha149** [comment]
Well at least it's solved then :)
If you change something in your pom.xml you need to tell IntelliJ to load the changes.
You can do this by opening the Maven tab in the top right corner and clicking on the reload button:

![explanation](https://github.com/Rapha149/SignGUI/assets/49787110/4852910d-a2b7-4d07-9a83-bd46ed642708)

**Comment by cmptrwhz** [comment]
Thank you very much for the information I will remember that for the future.
